import { JobPosting } from "@/types";

export const MOCK_JOB_POSTINGS: JobPosting[] = [
  // 1. SSC CGL 2026
  {
    id: "job-1",
    slug: "ssc-cgl-2026-recruitment",
    title: "SSC CGL 2026 Recruitment for 14,582 Group B & C Vacancies",
    shortSummary:
      "Staff Selection Commission (SSC) invites online applications for Combined Graduate Level (CGL) Examination 2026 for 14,582 posts including Assistant Section Officer, Inspector, and Tax Assistant.",
    organization: "Staff Selection Commission",
    organizationLogo: "",
    department: "Department of Personnel & Training (DoPT)",
    category: "government",
    status: "OPEN",
    location: "All India",
    totalVacancies: 14582,
    salaryOrStipend: "Pay Level 4 to Level 8 (₹25,500 - ₹1,51,100)",
    jobType: "Permanent",
    applicationMode: "Online",
    qualificationSummary: "Bachelor's Degree in any discipline from a recognized university",
    qualificationsList: [
      "Bachelor's Degree in any discipline from a recognized university or institute",
      "For Junior Statistical Officer (JSO): Bachelor's Degree in any subject with at least 60% Marks in Mathematics at 12th standard level or Bachelor's Degree with Statistics as one of the subjects",
      "For Statistical Investigator Grade-II: Bachelor's Degree in any subject with Statistics as one of the subjects for all three years",
      "Candidates appearing in the final year of graduation are also eligible to apply",
    ],
    importantDates: {
      notificationDate: "2026-06-15",
      applicationStartDate: "2026-06-15",
      applicationEndDate: "2026-07-24",
      lastDateFeePayment: "2026-07-25",
      correctionWindowDate: "2026-07-28 to 2026-07-30",
      examDate: "September - October 2026 (Tier 1)",
      admitCardDate: "August 2026",
      resultDate: "November 2026",
      answerKeyDate: "October 2026",
    },
    feeStructure: {
      general: "₹100",
      obc: "₹100",
      ews: "₹100",
      sc: "₹0 (Exempted)",
      st: "₹0 (Exempted)",
      female: "₹0 (Exempted)",
      ph: "₹0 (Exempted)",
      paymentMode: "Online via UPI, Net Banking, Debit/Credit Card, or SBI Challan",
      exemptionNotes: "All female candidates and SC/ST/PwD/ESM candidates are completely exempted from payment of fee.",
    },
    ageLimit: {
      minAge: 18,
      maxAge: 32,
      asOnDate: "01-08-2026",
      relaxationNotes: "OBC: 3 Years, SC/ST: 5 Years, PwD (Unreserved): 10 Years, PwD (OBC): 13 Years, PwD (SC/ST): 15 Years, Ex-Servicemen: 3 Years after deduction of military service.",
    },
    vacancyBreakdown: [
      {
        postName: "Assistant Section Officer (CSS, IB, MEA, MoD)",
        totalVacancies: 3420,
        qualification: "Bachelor's Degree in any stream",
        payScale: "Pay Level 7 (₹44,900 - ₹1,42,400)",
      },
      {
        postName: "Inspector (Central Excise, Preventive Officer, Examiner - CBIC)",
        totalVacancies: 4180,
        qualification: "Bachelor's Degree in any stream",
        payScale: "Pay Level 7 (₹44,900 - ₹1,42,400)",
      },
      {
        postName: "Assistant Enforcement Officer (ED) & Sub Inspector (CBI)",
        totalVacancies: 950,
        qualification: "Bachelor's Degree in any stream",
        payScale: "Pay Level 7 (₹44,900 - ₹1,42,400)",
      },
      {
        postName: "Auditor & Junior Accountant (CAG, CGA, CGDA)",
        totalVacancies: 2850,
        qualification: "Bachelor's Degree in any stream",
        payScale: "Pay Level 5 (₹29,200 - ₹92,300)",
      },
      {
        postName: "Tax Assistant & Upper Division Clerk (CBDT, CBIC, Ministries)",
        totalVacancies: 3182,
        qualification: "Bachelor's Degree + Data Entry Speed (8,000 key depressions/hour)",
        payScale: "Pay Level 4 (₹25,500 - ₹81,100)",
      },
    ],
    selectionProcess: [
      "Tier-1 Examination: Computer-Based Objective Test (Qualifying in nature — 200 Marks)",
      "Tier-2 Examination: Computer-Based Test (Mathematical Abilities, Reasoning, English, General Awareness, Computer Knowledge)",
      "Data Entry Speed Test (DEST): Mandatory qualifying typing test for specified posts",
      "Document Verification (DV): Verification of original academic and caste certificates by respective user departments",
      "Medical Examination: Physical standards and medical test as mandated by recruiting ministries",
    ],
    howToApplySteps: [
      "Visit the official Staff Selection Commission website at https://ssc.gov.in.",
      "Complete the One Time Registration (OTR) if not registered previously by providing Aadhaar/ID details, contact number, and personal profile.",
      "Log in to the candidate dashboard using your Registration Number and Password.",
      "Under 'Live Examinations', locate 'Combined Graduate Level Examination, 2026' and click on 'Apply'.",
      "Upload live captured webcam photograph ensuring clear lighting, no cap/glasses, and upload scanned signature (10–20 KB, JPEG/JPG format).",
      "Select your preferred examination centers in order of priority (up to 3 centers in the same SSC region).",
      "Verify educational qualification details, subject choices, and age relaxation claims.",
      "Preview the complete application form carefully. Correct any typographical errors before final submission.",
      "Pay the application fee of ₹100 online (if applicable) through UPI, Net Banking, or Credit/Debit Card.",
      "Download and print the finalized application confirmation receipt for future reference.",
    ],
    importantLinks: [
      {
        label: "Apply Online (Official SSC Portal)",
        url: "https://ssc.gov.in",
        linkType: "apply_online",
        isExternal: true,
      },
      {
        label: "Download Official Notification PDF",
        url: "https://ssc.gov.in/notices",
        linkType: "official_notification_pdf",
        isExternal: true,
      },
      {
        label: "Official SSC Website",
        url: "https://ssc.gov.in",
        linkType: "official_website",
        isExternal: true,
      },
    ],
    faqs: [
      {
        question: "What is the educational qualification required for SSC CGL 2026?",
        answer: "A Bachelor's Degree in any discipline from a recognized University or equivalent. Candidates appearing in their final year of graduation are also eligible to apply provided they acquire the essential qualification on or before the crucial cut-off date.",
      },
      {
        question: "What is the age limit for SSC CGL 2026 recruitment?",
        answer: "The age limit ranges between 18 to 32 years depending upon the specific post applied for as on 01-08-2026. Age relaxation of 3 years for OBC, 5 years for SC/ST, and up to 15 years for PwD candidates is admissible as per government rules.",
      },
      {
        question: "Is there any negative marking in the SSC CGL Tier-1 exam?",
        answer: "Yes, there is a negative marking of 0.50 marks for each wrong answer in the Tier-1 examination. In Tier-2 Paper-I, there is a negative marking of 1 mark for each wrong answer in Section-I, Section-II, and Module-I of Section-III.",
      },
      {
        question: "What is the application fee for female and reserved category candidates?",
        answer: "All female candidates and candidates belonging to Scheduled Caste (SC), Scheduled Tribe (ST), Persons with Benchmark Disabilities (PwD), and Ex-Servicemen (ESM) eligible for reservation are completely exempted from payment of the application fee.",
      },
    ],
    viewsCount: 48520,
    isFeatured: true,
    isTrending: true,
    isVerified: true,
    createdAt: "2026-06-15T10:00:00Z",
    updatedAt: "2026-06-16T14:30:00Z",
  },

  // 2. UPSC Civil Services
  {
    id: "job-2",
    slug: "upsc-civil-services-2026-prelims",
    title: "UPSC Civil Services Examination (CSE) 2026 — IAS / IPS / IFS",
    shortSummary:
      "Union Public Service Commission (UPSC) has notified 1,056 vacancies for Indian Administrative Service, Indian Police Service, and Indian Foreign Service through CSE 2026.",
    organization: "Union Public Service Commission",
    organizationLogo: "",
    department: "Cabinet Secretariat",
    category: "government",
    status: "OPEN",
    location: "All India",
    totalVacancies: 1056,
    salaryOrStipend: "Pay Level 10 (₹56,100 - ₹1,77,500) + DA, HRA",
    jobType: "Permanent",
    applicationMode: "Online",
    qualificationSummary: "Graduation degree in any stream from a UGC recognized university",
    qualificationsList: [
      "Bachelor's Degree in any discipline from a recognized University or Institute established by an Act of Parliament",
      "Candidates appearing for their degree examination are also eligible for the Preliminary Examination",
      "No minimum percentage restriction; pass class in degree is acceptable",
    ],
    importantDates: {
      notificationDate: "2026-02-14",
      applicationStartDate: "2026-02-14",
      applicationEndDate: "2026-03-05",
      lastDateFeePayment: "2026-03-05",
      examDate: "2026-05-24 (Prelims)",
      admitCardDate: "May 2026",
      resultDate: "June 2026 (Prelims)",
    },
    feeStructure: {
      general: "₹100",
      obc: "₹100",
      ews: "₹100",
      sc: "₹0 (Exempted)",
      st: "₹0 (Exempted)",
      female: "₹0 (Exempted)",
      ph: "₹0 (Exempted)",
      paymentMode: "Online via SBI Net Banking, Cards, UPI or Cash in SBI branch",
      exemptionNotes: "Female/SC/ST/Persons with Benchmark Disability candidates are exempted from fee.",
    },
    ageLimit: {
      minAge: 21,
      maxAge: 32,
      asOnDate: "01-08-2026",
      relaxationNotes: "OBC: 3 Years (Max 9 attempts), SC/ST: 5 Years (Unlimited attempts), PwD: 10 Years.",
    },
    vacancyBreakdown: [
      {
        postName: "Indian Administrative Service (IAS)",
        totalVacancies: 180,
        qualification: "Bachelor's Degree in any discipline",
        payScale: "Pay Level 10 (₹56,100 - ₹1,77,500)",
      },
      {
        postName: "Indian Police Service (IPS)",
        totalVacancies: 200,
        qualification: "Bachelor's Degree in any discipline",
        payScale: "Pay Level 10 (₹56,100 - ₹1,77,500)",
      },
      {
        postName: "Indian Foreign Service (IFS)",
        totalVacancies: 45,
        qualification: "Bachelor's Degree in any discipline",
        payScale: "Pay Level 10 (₹56,100 - ₹1,77,500)",
      },
      {
        postName: "Central Services Group 'A' (IRS, IA&AS, IDAS, etc.)",
        totalVacancies: 531,
        qualification: "Bachelor's Degree in any discipline",
        payScale: "Pay Level 10 (₹56,100 - ₹1,77,500)",
      },
      {
        postName: "Group 'B' Services (DANICS, DANIPS, Armed Forces HQ)",
        totalVacancies: 100,
        qualification: "Bachelor's Degree in any discipline",
        payScale: "Pay Level 8 (₹47,600 - ₹1,51,100)",
      },
    ],
    selectionProcess: [
      "Preliminary Examination (Objective): Paper I (General Studies) + Paper II (CSAT - 33% qualifying)",
      "Main Examination (Written Descriptive): 9 Papers (Total 1750 Marks)",
      "Personality Test / Interview: Conducted at UPSC Dholpur House, New Delhi (275 Marks)",
      "Final Merit Ranking & Cadre Allocation based on aggregate Main + Interview marks",
    ],
    howToApplySteps: [
      "Navigate to the official UPSC OTR portal at https://upsconline.nic.in.",
      "Register via One Time Registration (OTR) profile with valid email ID and mobile number.",
      "Fill in Part-I registration details including examination center preferences and photo identity proof.",
      "Upload scanned photo and signature as per prescribed pixel and file size parameters.",
      "Pay application fee of ₹100 via online banking or offline challan (exempted categories skip payment).",
      "Complete Part-II registration and accept the declaration to submit the CSE 2026 application.",
    ],
    importantLinks: [
      {
        label: "UPSC OTR & Online Application",
        url: "https://upsconline.nic.in",
        linkType: "apply_online",
        isExternal: true,
      },
      {
        label: "Download UPSC CSE Notification PDF",
        url: "https://upsc.gov.in",
        linkType: "official_notification_pdf",
        isExternal: true,
      },
      {
        label: "Official UPSC Website",
        url: "https://upsc.gov.in",
        linkType: "official_website",
        isExternal: true,
      },
    ],
    faqs: [
      {
        question: "How many attempts are allowed in UPSC CSE?",
        answer: "General category candidates are permitted 6 attempts up to 32 years of age. OBC candidates have 9 attempts up to 35 years. SC/ST candidates have unlimited attempts up to 37 years.",
      },
      {
        question: "Is CSAT marks counted for merit in UPSC Prelims?",
        answer: "No, General Studies Paper-II (CSAT) is a qualifying paper with minimum qualifying marks fixed at 33%. Only GS Paper-I marks determine shortlisting for the Mains Examination.",
      },
    ],
    viewsCount: 89400,
    isFeatured: true,
    isTrending: true,
    isVerified: true,
    createdAt: "2026-02-14T09:00:00Z",
    updatedAt: "2026-02-14T09:00:00Z",
  },

  // 3. RRB NTPC
  {
    id: "job-3",
    slug: "rrb-ntpc-2026-graduate-recruitment",
    title: "RRB NTPC 2026 Recruitment for 11,558 Graduate & Under-Graduate Posts",
    shortSummary:
      "Railway Recruitment Boards (RRB) Centralized Employment Notice (CEN 05/2026) for Station Master, Goods Train Manager, Junior Clerk, and Commercial Apprentice.",
    organization: "Railway Recruitment Control Board",
    organizationLogo: "",
    department: "Ministry of Railways",
    category: "government",
    status: "ENDING_SOON",
    location: "All India",
    totalVacancies: 11558,
    salaryOrStipend: "7th CPC Level 2 to Level 6 (₹19,900 - ₹35,400 Basic)",
    jobType: "Permanent",
    applicationMode: "Online",
    qualificationSummary: "12th Pass or Bachelor's Degree depending on post",
    qualificationsList: [
      "For Under-Graduate Posts (Level 2 & 3): 12th (+2 Stage) or its equivalent examination with not less than 50% marks in aggregate",
      "For Graduate Posts (Level 4, 5 & 6): University Degree in any discipline from a recognized University or its equivalent",
      "Typing proficiency in English (30 wpm) or Hindi (25 wpm) for clerical posts",
    ],
    importantDates: {
      notificationDate: "2026-09-10",
      applicationStartDate: "2026-09-14",
      applicationEndDate: "2026-10-13",
      lastDateFeePayment: "2026-10-14",
      correctionWindowDate: "2026-10-16 to 2026-10-25",
      examDate: "December 2026 - January 2027 (CBT-1)",
      admitCardDate: "To be announced",
      resultDate: "To be announced",
    },
    feeStructure: {
      general: "₹500 (₹400 refunded after CBT-1)",
      obc: "₹500 (₹400 refunded after CBT-1)",
      ews: "₹500 (₹400 refunded after CBT-1)",
      sc: "₹250 (Full ₹250 refunded after CBT-1)",
      st: "₹250 (Full ₹250 refunded after CBT-1)",
      female: "₹250 (Full ₹250 refunded after CBT-1)",
      ph: "₹250 (Full ₹250 refunded after CBT-1)",
      paymentMode: "Online via Internet Banking, UPI, Debit/Credit Card",
      exemptionNotes: "Candidates appearing in CBT-1 will receive refund of examination fee (less bank charges).",
    },
    ageLimit: {
      minAge: 18,
      maxAge: 33,
      asOnDate: "01-01-2026",
      relaxationNotes: "OBC: 3 Years, SC/ST: 5 Years, PwD: 10 Years as per Railway rules.",
    },
    vacancyBreakdown: [
      {
        postName: "Station Master (Level 6)",
        totalVacancies: 3820,
        qualification: "Bachelor's Degree + CBAT",
        payScale: "Level 6 (₹35,400 Basic)",
      },
      {
        postName: "Goods Train Manager (Level 5)",
        totalVacancies: 3140,
        qualification: "Bachelor's Degree in any stream",
        payScale: "Level 5 (₹29,200 Basic)",
      },
      {
        postName: "Junior Account Assistant cum Typist (Level 5)",
        totalVacancies: 1500,
        qualification: "Bachelor's Degree + Typing Skill",
        payScale: "Level 5 (₹29,200 Basic)",
      },
      {
        postName: "Junior Clerk cum Typist (Level 2)",
        totalVacancies: 3098,
        qualification: "12th Pass (+2) with 50% + Typing",
        payScale: "Level 2 (₹19,900 Basic)",
      },
    ],
    selectionProcess: [
      "1st Stage Computer Based Test (CBT-1) — Screening Test for all posts",
      "2nd Stage Computer Based Test (CBT-2) — Separate for each pay level",
      "Computer Based Aptitude Test (CBAT) for Station Master posts",
      "Typing Skill Test (TST) for Clerk and Typist posts",
      "Document Verification (DV) & Comprehensive Medical Examination",
    ],
    howToApplySteps: [
      "Visit the official centralized RRB application portal at https://www.rrbapply.gov.in.",
      "Click on 'Create an Account' and complete basic verification.",
      "Login with registered mobile number and password.",
      "Select CEN 05/2026 (NTPC) and choose your preferred Railway RRB Zone.",
      "Fill in educational qualifications, community details, and priority of posts.",
      "Upload digital color photograph with plain background and clear signature.",
      "Pay the application fee online through UPI or net banking.",
      "Submit and save the application confirmation page.",
    ],
    importantLinks: [
      {
        label: "Apply via Official RRB Portal",
        url: "https://www.rrbapply.gov.in",
        linkType: "apply_online",
        isExternal: true,
      },
      {
        label: "Official Notification PDF",
        url: "https://indianrailways.gov.in",
        linkType: "official_notification_pdf",
        isExternal: true,
      },
    ],
    faqs: [
      {
        question: "Can 12th pass students apply for RRB NTPC?",
        answer: "Yes, candidates who have passed 12th standard with at least 50% marks are eligible for Level 2 and Level 3 Under-Graduate posts such as Junior Clerk cum Typist and Accounts Clerk.",
      },
    ],
    viewsCount: 65120,
    isFeatured: true,
    isTrending: true,
    isVerified: true,
    createdAt: "2026-09-10T12:00:00Z",
    updatedAt: "2026-09-12T16:00:00Z",
  },

  // 4. Google India Software Engineer
  {
    id: "job-6-google",
    slug: "google-india-software-engineer-early-career-2026",
    title: "Google India Software Engineer (Early Career / University Graduate) 2026",
    shortSummary:
      "Google India is hiring Software Engineers for Bengaluru, Hyderabad, and Pune campuses to work on distributed systems, Cloud, Search, and Android platforms.",
    organization: "Google India Pvt Ltd",
    organizationLogo: "",
    department: "Core Engineering & Cloud",
    category: "private",
    status: "OPEN",
    location: "Karnataka",
    totalVacancies: "Multiple Openings",
    salaryOrStipend: "Competitive Tech Package (₹18 - ₹32 LPA CTC)",
    jobType: "Full Time",
    applicationMode: "Online",
    qualificationSummary: "B.Tech / B.E. / M.Tech / MCA in Computer Science or related STEM field",
    qualificationsList: [
      "Bachelor's or Master's degree in Computer Science, Computer Engineering, or related technical field",
      "Experience with software development in one or more general-purpose programming languages (Java, C++, Python, Go)",
      "Strong foundation in data structures, algorithms, and object-oriented software design",
    ],
    importantDates: {
      applicationStartDate: "2026-01-10",
      applicationEndDate: "2026-03-31",
      examDate: "Rolling Assessments",
      admitCardDate: "To be announced",
      resultDate: "To be announced",
    },
    feeStructure: {
      general: "₹0 (Free Application)",
      obc: "₹0 (Free Application)",
      ews: "₹0 (Free Application)",
      sc: "₹0 (Free Application)",
      st: "₹0 (Free Application)",
      female: "₹0 (Free Application)",
      ph: "₹0 (Free Application)",
      paymentMode: "N/A (Direct Corporate Hiring)",
      exemptionNotes: "Google never charges any application or processing fee.",
    },
    ageLimit: {
      minAge: 20,
      maxAge: 35,
      asOnDate: "01-01-2026",
      relaxationNotes: "Equal opportunity employer; no statutory age barriers.",
    },
    vacancyBreakdown: [
      {
        postName: "Software Engineer (Backend / Cloud)",
        totalVacancies: "50+ Positions",
        qualification: "B.Tech/M.Tech in CS/IT",
        payScale: "₹22 - ₹32 LPA CTC",
      },
      {
        postName: "Software Engineer (Frontend / Web)",
        totalVacancies: "30+ Positions",
        qualification: "B.Tech/MCA with React/TS expertise",
        payScale: "₹18 - ₹26 LPA CTC",
      },
    ],
    selectionProcess: [
      "Online Coding Assessment (2 algorithmic coding problems on data structures)",
      "Technical Phone Screen with a Google Senior Software Engineer (45 minutes)",
      "Onsite / Virtual Technical Interviews (3-4 rounds on Algorithms, System Architecture & Googleyness)",
      "Hiring Committee Review & Offer Rollout",
    ],
    howToApplySteps: [
      "Visit Google Careers at https://careers.google.com.",
      "Search for 'Software Engineer, Early Career, India'.",
      "Upload your PDF resume detailing programming languages, open-source projects, and GitHub links.",
      "Fill in education history, work experience, and location preferences.",
      "Review and submit your application.",
    ],
    importantLinks: [
      {
        label: "Apply via Google Careers",
        url: "https://careers.google.com",
        linkType: "apply_online",
        isExternal: true,
      },
      {
        label: "Google Student Guide",
        url: "https://careers.google.com/students",
        linkType: "official_website",
        isExternal: true,
      },
    ],
    faqs: [
      {
        question: "Can 2026 graduating students apply for Google India?",
        answer: "Yes, graduating students in their final year of B.Tech/B.E./M.Tech/MCA programs are eligible for early career university graduate hiring.",
      },
    ],
    viewsCount: 41200,
    isFeatured: true,
    isTrending: true,
    isVerified: true,
    createdAt: "2026-01-10T11:00:00Z",
    updatedAt: "2026-01-12T15:00:00Z",
  },
];
